# Generated by Django 4.1.7 on 2023-03-22 11:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='UserFavourites',
        ),
    ]
